---
title: "LEARNIT"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
    theme: readable
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(shiny)
library(plyr)
library(dplyr)
library(plotly)
library(tm)
```

```{r}
DATA = read.csv("D:/3-1 Rshiny/IMDB-Movie-Data.csv")
```

```{r}
DATA$Genre2 = DATA$Genre

DATA$Genre2=gsub(","," ",DATA$Genre2)

CORPUS=Corpus(VectorSource(DATA$Genre2))
CORPUS_TM = tm_map(CORPUS,removePunctuation)
CORPUS_TM = tm_map(CORPUS_TM, removeNumbers)
CORPUS_TM = tm_map(CORPUS_TM, tolower)

DTM = DocumentTermMatrix(CORPUS_TM)

DTM = as.data.frame(as.matrix(DTM))

DATA = cbind(DATA,DTM)

FIRST_GENRE = c()
for(i in 1:nrow(DATA)){
  FIRST_GENRE[i] = strsplit(as.character(DATA$Genre[i]),",")[[1]][1]
}

DATA$FIRST_GENRE = FIRST_GENRE
```


DASHBOARD CREATING {data-icon="fa-signal"}
==========================
Column {.sidebar}
--------------------------
  
```{r}
date()
```

Learnit Job Class    
Description :

1. 대시보드 만들기      
2. 새로운 평가지표 만들어보기    
3. 그래프 이쁘게 그려보기    
4. 유지보수 잘하기    

```{r}
selectInput('Genre', 'Genre',DATA$FIRST_GENRE,
            selected = 'action')

numericInput("Rating", "min Rating:", 6)
    
```

Row {data-height=100}
------------------------
### Target Of Dashboard

parameter 설정에 따라 변경되는 동적 대시보드 만들기

Row
--------------------------------
### Total Movies

```{r}
valueBox(value = paste(nrow(DATA),"movies"),
         color='royalblue')
```

### Selected Movies
```{r}

selectedData = reactive({
  subset(DATA,FIRST_GENRE==input$Genre)
})

```

```{r}

renderValueBox({
  valueBox(
    value = nrow(selectedData()),
    icon = "fa-area-chart",
    color = ifelse(nrow(selectedData()) < 50, "warning", "primary")
  )
})

```

### Ratings Gauge

```{r}

renderGauge({
  gauge(round(mean(selectedData()$Metascore,na.rm = TRUE),2), 
        min = 0, max = 100, 
      gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))
})

```


Row {data-width=650}
------------------------ 
### 년도별 영화 매출 추이(전체)

```{r}

 YEAR1 = DATA %>%
  group_by(Year) %>%
  dplyr::summarise(MEAN = mean(Revenue..Millions.,na.rm = TRUE),
                   MEDIAN = median(Revenue..Millions.,na.rm = TRUE))
 p = ggplot(YEAR1) +
  geom_line(aes(x=Year,y=MEAN),group = 1 , col ='red') +
  geom_point(aes(x=Year,y=MEAN), col ='red') +
  geom_line(aes(x=Year,y=MEDIAN),group = 1 , col = 'royalblue') +
  geom_point(aes(x=Year,y=MEDIAN) , col = 'royalblue') +
  xlab("년도") + ylab("매출액") 
 
 ggplotly(p)
 
```

### 년도별 영화 매출 추이(장르 선택)

```{r}

renderPlotly({
 YEAR2 = selectedData() %>%
  group_by(Year) %>%
  dplyr::summarise(MEAN = mean(Revenue..Millions.,na.rm = TRUE),
                   MEDIAN = median(Revenue..Millions.,na.rm = TRUE))
 p = ggplot(YEAR2) +
  geom_line(aes(x=Year,y=MEAN),group = 1 , col ='red') +
  geom_point(aes(x=Year,y=MEAN), col ='red') +
  geom_line(aes(x=Year,y=MEDIAN),group = 1 , col = 'royalblue') +
  geom_point(aes(x=Year,y=MEDIAN) , col = 'royalblue') +
  xlab("년도") + ylab("매출액") 
 
 ggplotly(p)
})

```

Row {data-width=650}
------------------------ 
### 데이터 테이블
```{r}
selectedData2 = reactive({
  subset(DATA,FIRST_GENRE==input$Genre & Rating > input$Rating)
})
```

```{r}
renderTable({
 DF = selectedData2()[,c(2,3,5:10,34)]
 DF[order(-DF$Rating),]
})

```