---
title: "homework 1015"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: yeti
---
```{r}
#교수님 코드 정리본 - 이코드 활용
# 1. ui ---- 
ui = fluidPage(
# 1.1. title ----
  titlePanel("붓꽃자료 산점도"),
# 1.2. sidebar ----
  sidebarLayout(
    sidebarPanel(helpText("붓꽃 종과 산점도를 그리 두 변수를 선택하세요."),
# 1.2.1. checkbox ----
      checkboxGroupInput("species",label = "종 선택", 
                         choices = list("setosa", "versicolor", "virginica"),
                         selected = c("setosa",  "versicolor", "virginica" )),
# 1.2.2. selectInput1 ----
      selectInput("x_name",label = "x축 변수",
           choices = list("Sepal.Length", "Sepal.Width", 
                         "Petal.Length", "Petal.Width"),
           selected = "Sepal.Length"),
# 1.2.3. selectInput2 ----
      selectInput("y_name",label = "y축 변수",
           choices = list("Sepal.Length", "Sepal.Width", 
                         "Petal.Length", "Petal.Width"),
           selected = "Sepal.Width"),
), #sidebarPenel
# 1.3. mainPanel(output) ----
    mainPanel(
# 1.3.1. plot(output) ----
plotOutput("out")
) #mainPanel
) #sidebarLayout
) #fluidPage

# 2. server ----
server=function(input, output){
output$out=renderPlot({
# 2.1. 종 선택 안하면 빈 plot
if(is.null(input$species)) {return()}
# 2.2. 입력 종과 일치하는 행만 선택
row=which(iris$Species %in% input$species)
# 2.3. 선택 행 중에서 입력한 변수에 대응하는 열을 선택
x=iris[row, input$x_name]; y=iris[row, input$y_name]
# 2.4. 산점도 셋팅
col=rep(0,dim(iris)[1])
col[iris$Species == "setosa"]="deeppink"
col[iris$Species == "versicolor"]="blue3"
col[iris$Species == "virginica"]="green3"
# 2.4. 산점도
plot(x,y, col=col[row], cex=2, main="산점도" )
legend("topright", box.col='gray', horiz=TRUE, 
        inset=0.01, bg="transparent",
        legend=input$species, 
        text.col=unique(col[row]))
}) # renderPlot
} #server

shinyApp(ui, server)
```


```{r setup, include=FALSE}
library(tidyverse)
library(googlesheets4)
library(flexdashboard)
library(plotly)

# Make googlesheets4 not try to authenticate, since we're using a public sheet
#sheets_deauth()
```

```{r get-data, message=FALSE, include=FALSE}
# The 1RKNn84xVLUanhGyX8DPvDSd8zt4GX_eBmK2ZX2nf0BI comes from the shared link
# URL from Google Sheets. You can also refer to sheets by name if you're
# authenticated into your account. See the googlesheets4 documentation for more
# details
remote_data <- read.csv("https://raw.githubusercontent.com/HakJun-Song/class/master/dashboard_test.csv")

```

## Row

### Categories {.value-box}

```{r}
# Find the number of unique categories
checkboxGroupInput("species",label = "종 선택",choices = list("setosa", "versicolor", "virginica"), selected = c("setosa",  "versicolor", "virginica" ))

# Show the number in a special valueBox (note the {.value-box} CSS class
# above—that applies the CSS class to the HTML output and makes it render
# correctly)
valueBox(value = n_categories, icon = "fas fa-users")
```

### Total {.value-box}

```{r}
# Get a total of all the counts
total <- sum(remote_data$Count)

# Show the number in a valueBox
valueBox(value = total, icon = "fas fa-cubes")
```

## Row

###

```{r}
# Make a basic column plot
my_plot <- ggplot(remote_data, aes(x = Category, y = Count)) +
  geom_col(aes(text = Count)) +
  theme_minimal()

# Show the plot with plotly
ggplotly(my_plot, tooltip = "text")
```